version: "3.7"

services:
  mongo:
    container_name: 'vold_database'
    image: mongo:latest
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - '27017-27019:27017-27019'

  database_manager:
    container_name: 'vold_database_manager'
    image: mongo-express:latest
    restart: on-failure
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
